color = input("Enter a color: ")
plural_noun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity: ")
celebrity2 = input("Enter another celebrity: ")
print(f"Roses are {color}")
print(f"{plural_noun} are blue")
print(f"I love {celebrity}")
print(f"And {celebrity2} too!")